- src/lib.rs
When calculating world space from screen space coordinates, a division by zero would occur if the projection had far plane set to infinity. Now a small non-zero value is used instead.
Closes #7
> Picking now works when far plane is at infinity

- demo/Cargo.toml
- demo/src/main.rs
- src/lib.rs
- src/rotation.rs
Fixes #14
Arcs in the rotation gizmo point in the wrong direction when using left-handed coordinate system. Now the forward vector is inverted for rotation gizmo in such case.
Also fixes snapping with ctrl & shift on Linux
> Rotation gizmo works with left-handed coordinate system

- src/lib.rs
Fixes #16.
*Multiple gizmos being interacted with on [my project](https://github.com/setzer22/blackjack)*
I'll also take the chance to say thanks for this amazing project :)
> Fix for multiple gizmos

- Cargo.toml
- demo/Cargo.toml
While waiting for https://github.com/optozorax/egui-macroquad/pull/29#issue-1498460381 to be accepted by egui.macroquad, demo's egui-macroquad dependency has been temporarily modified to https://github.com/matthiascy/egui-macroquad.git.
> Bump egui to v0.20, glam to v0.22.

- demo/src/main.rs
- src/lib.rs
- src/rotation.rs
- src/scale.rs
- src/translation.rs
Fixes #22
Config used for drawing the active subgizmo was not updated.
This would cause the gizmo to 'lag' behind the manipulated object,
because the gizmo drawing would use outdated information.
Now the subgizmo config is updated according to the interaction result.
Additionally:
The gizmo result now stores updated scale, rotation and translation instead of the transformation matrix.
The transformation matrix, both in Mat4 and array form, can be read with `GizmoResult::transform` and `GizmoResult::transform_cols_array_2d` respectively.
> Lag between gizmo and manipulated object

- Cargo.toml
- README.md
- demo/src/main.rs
- src/lib.rs
- src/rotation.rs
- src/scale.rs
- src/subgizmo.rs
- src/translation.rs
The public api is changed to use mint types instead of arrays and glam types, for consistency and clarity.
> #28 Public api uses mint types

- Cargo.toml
Just bumping the egui version and also the egui-gizmo version.
If this can be published to crates.io, that would be great.
> Update to egui 0.25

- Cargo.toml
- demo/Cargo.toml
- demo/src/main.rs
- src/lib.rs
- src/math.rs
- src/painter.rs
- src/subgizmo/common.rs
- src/subgizmo/rotation.rs
I Just saw the other PR here for the same thing https://github.com/urholaukkarinen/egui-gizmo/pull/40
However, I'm maintaining a fork of bevy-egui for other projects, so at least until the russian invasion of Ukraine is over, people have an up to date version of bevy_egui
Also added some lints
> Update to egui 0 26

- src/subgizmo/common.rs
When used in an external package it produces the following compilation error：
```log
error[E0446]: private type `GizmoConfig` in public interface
--> C:\Users\Varphone\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-gizmo-0.16.0\src\subgizmo\common.rs:312:1
|
312 | pub fn gizmo_local_normal(config: &GizmoConfig, direction: GizmoDirection) -> DVec3 {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
|
::: C:\Users\Varphone\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-gizmo-0.16.0\src\lib.rs:506:1
|
506 | pub(crate) struct GizmoConfig {
| ----------------------------- `GizmoConfig` declared as private
error[E0446]: private type `GizmoConfig` in public interface
--> …
```
> Fix `can't leak crate-private type` compile error

- src/painter.rs
Allows clipping the gizmo with the viewport to prevent it from rendering over other UI. Especially usefull with things like https://github.com/rerun-io/egui_tiles
> Clip gizmo painters with viewport

- crates/transform-gizmo-bevy/src/lib.rs
Found a problem where, if the Gizmo camera is parented to something, then the gizmo will appear off.
(In my top-down game the camera is parented to a "selfie stick" to make it easier to move without having to worry about its angle towards the ground)
The fix looked easy hence the PR, it should just read the GlobalTransform of the camera instead of the local.
In another branch I made a very rudimentary change to your example to showcase the bug, I only modified the scene.rs file: https://github.com/AlexAegis/transform-gizmo/blob/non-global-camera-bug-demo/examples/bevy/src/scene.rs
> Use GlobalTarget when reading the position of the Gizmo camera

- crates/transform-gizmo-bevy/src/lib.rs
> add support for custom viewport rects in bevy integration

- crates/transform-gizmo-bevy/src/lib.rs
- crates/transform-gizmo-egui/src/lib.rs
- crates/transform-gizmo/src/config.rs
- crates/transform-gizmo/src/gizmo.rs
- crates/transform-gizmo/src/subgizmo/arcball.rs
- crates/transform-gizmo/src/subgizmo/common.rs
- crates/transform-gizmo/src/subgizmo/scale.rs
- crates/transform-gizmo/src/subgizmo/translation.rs
- examples/bevy/src/gui.rs
- examples/bevy/src/main.rs
- examples/bevy/src/scene.rs
- examples/egui/src/main.rs
You can now configure each individual subgizmo separately. For example, you could configure the gizmo to only have a Z translation arrow and arcball rotation.
You can also configure a bunch of hotkeys that can be used to toggle different transformation modes without having to manually interact with the gizmo. This works very similarly compared to Blender. The hotkeys are disabled by default, but can be enabled via `GizmoConfig`. `GizmoHotkeys::default()` includes some sensible defaults.
> Add more granular gizmo mode configuration & hotkeys 

- Cargo.toml
- crates/transform-gizmo/src/shape.rs
- examples/egui/src/main.rs
For glam, this is transparent and didn't require any change.
egui replaced some `Stroke` with `PathStroke` (strokes that can have a uv callback to get the color instead of a single `Color32` for the whole stroke). I updated `shape.rs`  to take it into account. Only `arrow(..)` still uses a `Stroke` since it uses its color to fill the shape. Since the functions uses into conversions in their signatures this is also transparent outside of the file.
> Update egui to 0.28 and glam to 0.28

- Cargo.toml
- crates/transform-gizmo-bevy/Cargo.toml
- crates/transform-gizmo-bevy/examples/bevy_minimal.rs
- crates/transform-gizmo-bevy/src/lib.rs
- crates/transform-gizmo-bevy/src/render.rs
- examples/bevy/Cargo.toml
- examples/bevy/src/main.rs
- examples/bevy/src/scene.rs
- rust-toolchain
This PR allows transform-gizmo-bevy to be used with Bevy 0.14. Closes #66.
Before we merge this PR, we should probably take this opportunity to get #68 merged first (upgrade all the dependencies' versions at once).
----------------------------------------
Concretely, this implements the following migration steps:
- Upgrade bevy & its subcrates to 0.14
- Upgrade required rustc to 1.79.0 (from 1.77.0) as [required by Bevy](https://github.com/bevyengine/bevy/blob/v0.14.0/Cargo.toml#L13)
- https://github.com/bevyengine/bevy/pull/12313 : [Add bytemuck & util as dependencies](https://github.com/urholaukkarinen/transform-gizmo/commit/57657df4883efa47ec978097719ef08e62c2825b)
- https://github.com/bevyengine/bevy/pull/13489 : [Rename camera.projection_matrix to …
> Upgrade to Bevy 0.14

- Cargo.toml
- crates/transform-gizmo-bevy/Cargo.toml
- crates/transform-gizmo-egui/Cargo.toml
- crates/transform-gizmo/Cargo.toml
Requiring 1.79 is way too much. For example, nixOS unstable only has 1.78 right now.
This PR keeps 1.79 on Bevy-related stuff, while putting 1.76 on the rest.
> Lower the Rust requirements to 1.76

- crates/transform-gizmo-egui/src/lib.rs
The default gizmo viewport is `Rect::NOTHING`. Egui gizmo replaces non-finite viewports with the clip rect.
However, the non-finite viewport was being used for egui clipping even though the gizmo viewport was replaced.
> #72 Fixed egui gizmo rendering with the default viewport

- crates/transform-gizmo/src/gizmo.rs
Updated gizmo rotation quaternion was not normalized properly, causing accumulating errors in the rotation, eventually breaking the whole gizmo.
> Updated rotation is properly normalized (#77)

- crates/transform-gizmo/src/config.rs
- crates/transform-gizmo/src/gizmo.rs
Gizmo orientation is no longer forced to `Local` when scaling is enabled and scaling works properly with global orientation
> Implemented scaling with global orientation (#7)

- crates/transform-gizmo-egui/src/lib.rs
Painter's clip rect was always a sub-region of the UI's clip rect, so it was not possible to draw outside the used UI. Now the whole gizmo viewport is used as clip rect
> Fixed painter clipping in transform-gizmo-egui (#71)

- crates/transform-gizmo-bevy/src/lib.rs
- crates/transform-gizmo-egui/src/lib.rs
- crates/transform-gizmo/src/gizmo.rs
The gizmo can no longer be interacted with through other UI elements. For now this is only implemented in `transform-gizmo-egui`.
> Fixed gizmo responding to mouse input through other UI elements (#73)

- Cargo.toml
- crates/transform-gizmo-bevy/Cargo.toml
- crates/transform-gizmo-bevy/examples/ui_blocked_gizmo.rs
- crates/transform-gizmo-bevy/src/lib.rs
- crates/transform-gizmo-bevy/src/mouse_interact.rs
- crates/transform-gizmo-bevy/src/picking.rs
- crates/transform-gizmo-bevy/src/render.rs
- crates/transform-gizmo/src/shape.rs
- crates/transform-gizmo/src/subgizmo/common.rs
- crates/transform-gizmo/src/subgizmo/rotation.rs
- docs/bevy-example.js
- docs/index.html
- examples/bevy/Cargo.toml
- examples/bevy/src/camera.rs
- examples/bevy/src/gui.rs
- examples/bevy/src/main.rs
- examples/bevy/src/picking.rs
This PR cherry-picks changes from:
- https://github.com/urholaukkarinen/transform-gizmo/pull/90
- https://github.com/urholaukkarinen/transform-gizmo/pull/88
Additionally:
- Bevy demo is updated to use newer bevy_mod_outline and bevy_infinite_grid.
- Bevy demo was missing the infinite grid plugin, so that is restored
- Web demo is been updated
> Update bevy 0.16, fix spelling, update web demo

- crates/transform-gizmo-bevy/src/lib.rs
- crates/transform-gizmo/src/config.rs
It was possible to activate gizmo modes using hotkeys even if the modes were explicily disabled in GizmoOptions. That is no longer possible.
Now if you only have RotateZ mode enabled and press the rotation hotkey, the Z rotation will activate.
Also fixed another bug where hotkeys did not properly activate the gizmo if the gizmo was not hovered.
Fixes #87
> #87 Prevent hotkeys activating modes absent from GizmoOptions.gizmo_modes

- crates/transform-gizmo/src/subgizmo.rs
- crates/transform-gizmo/src/subgizmo/common.rs
- crates/transform-gizmo/src/subgizmo/scale.rs
- crates/transform-gizmo/src/subgizmo/translation.rs
- docs/bevy-example.js
- docs/index.html
Some subgizmos were not initially visibled until you hovered the gizmo. Also, if you toggled some of the modes in the GizmoOptions, the some subgizmos would disappear and only appear once hovered again.
The subgizmo opacity/visibility calculation is now done both in picking and drawing phase and not stored in the gizmo state.
> Fixed gizmo visibility not updating correctly when not hovered
